### ISSUE TITLE
LinHttpHandler.cpp:108.  LinHttpHandler: Failed to read response from socket: 104

### ISSUE THREAD

**Issue by yura0202** [enwi/hueplusplus#15]
LinHttpHandler.cpp:108

LinHttpHandler: Failed to read response from socket: 104
terminate called after throwing an instance of 'std::runtime_error'
  what():  LinHttpHandler: Failed to read response from socket

my code is:

	auto handler = std::make_shared<LinHttpHandler>();
	HueFinder finder(handler);
	std::vector<HueFinder::HueIdentification> bridges = finder.FindBridges();
	if (bridges.empty())
	{
		bridges.push_back({ HUE_IP, HUE_MAC});
	}
	
	finder.AddUsername(bridges[0].mac, HUE_USER_NAME);
	Hue bridge = finder.GetBridge(bridges[0]);
	
	auto m_lights = bridge.getAllLights();
	
	for (auto light : m_lights)
		light.get().On();

NOTE: it works sometimes, and sometimes throws an error.  

LinHttpHandler.cpp:105		ssize_t bytes = read(socketFD, buffer, 127);
I do not kow why but read() returns -1.

**Comment by Jojo-1000** [comment]
The error code 104 means "Connection reset by peer".

From https://stackoverflow.com/a/1434592:
> This means that a TCP RST was received and the connection is now closed. This occurs when a packet is sent from your end of the connection but the other end does not recognize the connection; it will send back a packet with the RST bit set in order to forcibly close the connection.
>
> This can happen if the other side crashes and then comes back up or if it calls close() on the socket while there is data from you in transit, and is an indication to you that some of the data that you previously sent may not have been received.

I found this issue https://github.com/eclipse/smarthome/issues/4794 which implies that the bridge limits the number of http requests (although the official documentation only mentions that an error JSON value is returned).
The problem is that in your loop you try to turn on all lights at once, without any delay in between. The easiest solution would be if we introduce a delay after every API call.

In the meantime, you could replace your loop with
```cpp
for (auto light : m_lights)
{
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    light.get().On();
}
```
and see if that works better for you.
