### ISSUE TITLE
Issues with using this in a container class

### ISSUE THREAD

**Issue by buelowp** [enwi/hueplusplus#26]
I love the design so far, but have some questions. 

1. Because the Hue object does not have a default constructor, I cannot create a member variable of type Hue very easily. Do you have thoughts about how to work around this? I would suggest changing the library to return pointers to a Hue object, to allow for both bridge IP known AND bridge IP not known situations. Then the member variable could just be a pointer to the Hue object, and created as needed either with FindBridge() or Hue(ip, key, handler). But I get that this would be a departure in design.
1. I can't seem to find a way to figure out how to track the connection state. Is there a way to figure out the connection is lost or to check if the connection is still good?

I'm working on a RPi touch screen for hue bulbs, and this library solves a lot of problems, specifically because it's up to date and seemingly very easy to use. But I don't see a way to figure out I have to restart the connection and I need a way to maintain the Hue object in class that lets me thread the Hue calls so they don't block the Qt UI.

Thank you.

**Comment by Jojo-1000** [comment]
1.  You can work around the missing default constructor with either `std::optional` or `std::unique_ptr`, depending on which c++ version you are using.
The idea behind FindBridges is that you can specify your bridge by MAC address, because depending on your router configuration, the IP might change. So the normal usage for reconnecting would be:

```c++
std::unique_ptr<Hue> bridge;
std::string bridgeMac;
std::string username;
// Read bridgeMac and username from a file
// ...

HueFinder finder(handler);
// Add existing username(s)
finder.AddUsername(bridgeMac, username);

std::vector<HueFinder::HueIdentification> bridges = finder.FindBridges();
// Find matching mac address
auto it = std::find_if(bridges.begin(), bridges.end(),
    [&](auto identification) { return identification.mac == bridgeMac; });
if(it == bridges.end()) {
    // Bridge not found, display error or selection dialog
} else {
    bridge = std::make_unique<Hue>(finder.GetBridge(*it));
}
```
If you are certain the IP does not change, you can of course use the constructor directly.

2.  There is no persistent connection to the Hue bridge, all calls are individual HTTP requests. As long as the bridge is available, these should not fail. If they do, they should throw an exception. In that case, all you can do is wait and retry until the bridge comes back online. You should not need to create a new Hue instance.
Are you getting problems with the connection, or do you just want to display the state?

**Comment by buelowp** [comment]
Yeah, shoot, my bad. I didn't even consider the C++ way to do this for my C++ problem. I got that coded up and it seems to do what I need it to now.

As for the state, I have the devices in a couple of places where networking isn't great, which on a Pi Zero means it's going to be challenging to do this the right way. If I get exceptions, I can easily handle the errors, but I may add a ping to the IP as a side mechanism to try to determine when networking isn't "working" and grey out the buttons to avoid forcing an error to happen. I may also tie into NetworkManager via DBus, but that's more work than I want to put into this right now.

Thanks again.
