### ISSUE TITLE
Missing support for new Bluetooth (Gen4) lights

### ISSUE THREAD

**Issue by EmilyBjoerk** [enwi/hueplusplus#58]
I got a new Hue light yesterday with bluetooth support (gen4) with the identifier `LTA001`. This caused hueplusplus to crash on enumerating the lights with:

```
Oct 28 11:49:37 raspberrypi photon-hue-service[24287]: terminate called after throwing an instance of 'std::runtime_error'
Oct 28 11:49:37 raspberrypi photon-hue-service[24287]:   what():  Could not determine HueLight type!
```

This is caused by the string "LTA001" missing from the check here:

https://github.com/enwi/hueplusplus/blob/83d4883211e61a66867f5736a96c667652ce333e/hueplusplus/Hue.cpp#L277

Presumably there are other new lights that are also missing that I don't know of.

In general I believe that the approach of enumerating all product IDs here to determine their capabilities is going to cause this class on sins of omission to continue appearing as new products are created by Philips. Is there no way to query the lights to get their capabilities  from the API so that a hard coded list like this isn't needed?

**Comment by Jojo-1000** [comment]
There is, and it is implemented on the development branch along with a bunch of other changes.

You can look at #57 for more detail, TL;DR:

- development branch has a lot of breaking changes, so release is planned once feature-complete
- capabilities only works for newer bridges
- I replaced this exception with a warning on the development branch, because the light is still usable even on older bridges
- the color conversion approach from RGB to XY and brightness (recommended by Hue) does not look consistent

I would be especially interested in feedback on the color conversion. Maybe it needs to be rolled back to only affect XY and leave brightness alone.

**Comment by EmilyBjoerk** [comment]
@enwi I'm using my fork that I've locked at an older commit with some of my fixes on. I don't currently have the time to rework my code to work with the breaking changes in the development branch. So unfortunately I haven't tested and will unlikely have the time to test. (I've applied a fix to my local fork for the light that I needed already).

**Comment by enwi** [comment]
Okay then I will close this issue.
